apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-frontend
  labels:
    app: test-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-frontend
    spec:
      containers:
        - image: IMAGETAG
          imagePullPolicy: Always
          name: test-frontend
          ports:
            - containerPort: 80
              protocol: TCP

###

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-frontend
spec:
  backend:
    serviceName: test-frontend
    servicePort: 80

###

apiVersion: v1
kind: Service
metadata:
  name: test-frontend
spec:
  selector:
    app: test-frontend
  type: LoadBalancer
  ports:
    -  protocol: TCP
       port: 80
       targetPort: 80
