AWSTemplateFormatVersion: 2010-09-09
Description:  Template for a cloudtrail trail

# TODO: Make Cloudwatch logging optional

Parameters:
  pEnvironment:
    Description: 'the environment the resource is being created in'
    Type: String
    Default: 'dev'
    AllowedValues:
      - 'dev'
      - 'prod'

  pOrgIdentifier:
    Description: 'Organizational identifier to use for resources.  Will be used as prefix.'
    Type: String
    Default: uniqueId

  pLogGroupRetentionInDays:
    Description: 'The number of days to retain cloudwatch logs for this trail'
    Type: String
    Default: 7
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1827
      - 3653

  pConfigureCloudwatchLogging:
    Description: 'Configure trail to log to cloudwatch?'
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

  pCreateSplunkManagedPolicy:
    Description: 'Create Splunk managed policy?'
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

Conditions:
  cConfigureCloudWatchLogging: !Equals [ !Ref pConfigureCloudwatchLogging, 'true' ]
  cCreateSplunkManagedPolicy: !Equals [ !Ref pCreateSplunkManagedPolicy, 'true' ]

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Organizational Details'
        Parameters:
          - pEnvironment
          - pOrgIdentifier
    ParameterLabels:
      pEnvironment:
        default: Development environment for this template
      pOrgIdentifier:
        default: Unique Organization Identifier


Resources:

  rCloudTrailManagedKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Join ["/", ["alias", !Join ["-", [!Ref pOrgIdentifier, !Ref pEnvironment, "cloudtrail-cmk", !Select [ "4", !Split [ "-", !Select [ "2", !Split [ "/", !Ref "AWS::StackId" ]]]]]]]]
      TargetKeyId: !Ref rCloudTrailManagedKey

  rCloudTrailManagedKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: Key to encrypt EKS secrets
      Enabled: true
      KeyPolicy:
        Version: 2012-10-17
        Id: !Join ["-", [!Ref pOrgIdentifier, !Ref pEnvironment, "cmk", !Select [ "4", !Split [ "-", !Select [ "2", !Split [ "/", !Ref "AWS::StackId" ]]]]]]
        Statement:
          - Sid: Allow Administration of Key
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - kms:*
            Resource: "*"
          - Sid: Allow use of Key
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action:
              - 'kms:Decrypt'
              - 'kms:Encrypt'
              - 'kms:ReEncrypt'
              - 'kms:GenerateDataKey'
              - 'kms:DescribeKey'
            Resource: '*'
          - Sid: Allow use of Key
            Effect: Allow
            Principal:
              AWS:
                - 'arn:aws:iam::${ACCOUNTID}:role/ROLENAME'
            Action:
              - kms:Decrypt
            Resource: "*"

  rCloudWatchLogsGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub ${pOrgIdentifier}-cloudtrail-logs-${AWS::AccountId}
      RetentionInDays: !Ref pLogGroupRetentionInDays

  rCloudWatchLogsStream:
    Condition: cConfigureCloudWatchLogging
    Type: 'AWS::Logs::LogStream'
    Properties:
      LogGroupName: !Ref rCloudWatchLogsGroup
      LogStreamName: !Sub CloudTrail_${AWS::AccountId}_stream

  rCloudTrailPolicy:
    Condition: cConfigureCloudWatchLogging
    DependsOn:
      - rCloudWatchLogsGroup
      - rCloudWatchLogsStream
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: !Sub ${pOrgIdentifier}-cloudtrail-cloudwatch-policy
      Description: 'policy for cloudtrail to create cloudwatch logs and put events'
      Path: "/"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - "Sid": 'AllowAWSCloudTrailCreateLogStream'
            "Effect": Allow
            "Resource": !GetAtt rCloudWatchLogsGroup.Arn
            "Action":
              - 'logs:CreateLogStream'
          - "Sid": 'AllowAWSCloudTrailPutLogEvents'
            "Effect": Allow
            "Resource": !GetAtt rCloudWatchLogsGroup.Arn
            "Action":
              - 'logs:PutLogEvents'

  rCloudTrailSplunkPolicy:
    Condition: cCreateSplunkManagedPolicy
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: !Sub ${pOrgIdentifier}-splunkAwsAddOn-policy
      Description: 'policy for Splunk Add-on for AWS'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'SplunkAWSAddOnSqs'
            Effect: 'Allow'
            Action:
              - sqs:GetQueueAttributes
              - sqs:ListQueues
              - sqs:ReceiveMessage
              - sqs:GetQueueUrl
              - sqs:SendMessage
              - sqs:DeleteMessage
            Resource:
              - '*'
          - Sid: 'SplunkAWSAddOnS3'
            Effect: 'Allow'
            Action:
              - s3:ListBucket
              - s3:GetObject
              - s3:GetBucketLocation
              - s3:ListAllMyBuckets
              - s3:GetBucketTagging
              - s3:GetAccelerateConfiguration
              - s3:GetBucketLogging
              - s3:GetLifecycleConfiguration
              - s3:GetBucketCORS
            Resource:
              - !GetAtt rCloudTrailBucket.Arn


  rCloudTrailBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join [ "-", [!Ref pEnvironment, !Ref pOrgIdentifier, 'cloudtrail', !Ref 'AWS::Region' ]]

  rCloudTrailBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref rCloudTrailBucket
      PolicyDocument:
        Id: !Join [ '-', [ !Ref pOrgIdentifier, 'cloudtrail-s3-policy', !Ref 'AWS::Region']]
        Version: '2012-10-17'
        Statement:
          #        We will uncomment this when we want to block to a specific subnet
          - Sid: 'AWSCloudTrailAclCheck'
            Effect: 'Allow'
            Principal:
              Service: 'cloudtrail.amazonaws.com'
            Action: 's3:GetBucketAcl'
            Resource:
              - !Sub arn:aws:s3:::${rCloudTrailBucket}
          - Sid: 'AWSCloudTrailWrite'
            Effect: 'Allow'
            Principal:
              Service: 'cloudtrail.amazonaws.com'
            Action: 's3:PutObject'
            Resource:
              - !Sub arn:aws:s3:::${rCloudTrailBucket}/AWSLogs/${AWS::AccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  rCloudTrailGroupRole:
     Type: 'AWS::IAM::Role'
     Properties:
       AssumeRolePolicyDocument:
         Version: '2012-10-17'
         Statement:
           - Effect: 'Allow'
             Principal:
               Service: 'cloudtrail.amazonaws.com'
             Action: 'sts:AssumeRole'
       Policies:
         - PolicyName: !Sub ${pOrgIdentifier}-${AWS::AccountId}-cloudtrail-cloudwatch-policy-${AWS::Region}
           PolicyDocument:
             Version: '2012-10-17'
             Statement:
               - Effect: 'Allow'
                 Action:
                   - 'logs:CreateLogStream'
                   - 'logs:PutLogEvents'
                 Resource: !GetAtt rCloudWatchLogsGroup.Arn

  rCloudTrailTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: !Sub ${pOrgIdentifier}-${AWS::AccountId}-cloudtrail-sns-topic-${AWS::Region}
      DisplayName: !Sub ${pOrgIdentifier}-cloudtrail

  rCloudTrailTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CloudTrailSnsPolicy
            Effect: 'Allow'
            Principal:
              Service: 'cloudtrail.amazonaws.com'
            Resource: !Ref rCloudTrailTopic
            Action: 'sns:Publish'
      Topics:
        - !Ref rCloudTrailTopic

  rCloudTrailSqsQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Sub ${pOrgIdentifier}-${AWS::AccountId}-cloudtrail-sqs-queue-${AWS::Region}

  rCloudTrailSqsQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CloudTrailSQSPolicy
            Effect: 'ALlow'
            Principal:
              Service: 'cloudtrail.amazonaws.com'
            Resource: !Ref rCloudTrailSqsQueue
            Action:
              - 'sqs:ReceiveMessage'
          - Sid: CloudTrailSQSPolicySNS
            Effect: 'ALlow'
            Principal:
              Service: 'sns.amazonaws.com'
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref rCloudTrailTopic
            Resource: !GetAtt rCloudTrailSqsQueue.Arn
            Action:
              - 'sqs:SendMessage'
      Queues:
        - !Ref rCloudTrailSqsQueue

  rCloudTrailSnsSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref rCloudTrailTopic
      Endpoint: !GetAtt rCloudTrailSqsQueue.Arn
      Protocol: sqs
      RawMessageDelivery: 'true'


  rCloudTrail:
    DependsOn:
      - rCloudTrailBucketPolicy
      - rCloudTrailManagedKeyAlias
    Type: 'AWS::CloudTrail::Trail'
    Properties:
      TrailName: !Sub ${pOrgIdentifier}-${AWS::AccountId}-cloudtrail-trail-${AWS::Region}
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      EnableLogFileValidation: true
      KMSKeyId: !Ref rCloudTrailManagedKey
      S3BucketName: !Ref rCloudTrailBucket
      IsLogging: true
      CloudWatchLogsLogGroupArn: !If [cConfigureCloudWatchLogging, !GetAtt rCloudWatchLogsGroup.Arn, !Ref 'AWS::NoValue']
      CloudWatchLogsRoleArn: !If [cConfigureCloudWatchLogging, !GetAtt rCloudTrailGroupRole.Arn, !Ref 'AWS::NoValue']
      SnsTopicName: !GetAtt rCloudTrailTopic.TopicName


Outputs:

  oCloudTrailManagedKeyAlias:
    Description: 'alias name'
    Value: !Ref rCloudTrailManagedKeyAlias
    Export:
      Name: !Sub '${AWS::StackName}-o3BucketArn'

  oCloudTrailManagedKey:
    Description: 'KMS key ARN'
    Value: !GetAtt rCloudTrailManagedKey.Arn
    Export:
      Name: !Sub '${AWS::StackName}-oCloudTrailManagedKey'

  oCloudWatchLogsGroup:
    Description: 'LogsGroup ARN'
    Value: !GetAtt rCloudWatchLogsGroup.Arn
    Export:
      Name: !Sub '${AWS::StackName}-oCloudWatchLogsGroup'

  oCloudWatchLogsStream:
    Description: 'LogsStream Name'
    Value: !Ref rCloudWatchLogsStream
    Export:
      Name: !Sub '${AWS::StackName}-oCloudWatchLogsStream'

  oCloudTrailPolicy:
    Description: 'Cloudtrail Managed Policy Arn'
    Value: !Ref rCloudTrailPolicy
    Export:
      Name: !Sub '${AWS::StackName}-oCloudTrailPolicy'

  oCloudTrailGroupRole:
    Description: 'CloudTrail Role Arn'
    Value: !GetAtt rCloudTrailGroupRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-oCloudTrailGroupRole'

  oCloudTrailBucket:
    Description: 's3 bucket arn'
    Value: !GetAtt rCloudTrailBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-oCloudTrailBucket'


  oCloudTrail:
    Description: 'CloudTrail Arn'
    Value: !GetAtt rCloudTrail.Arn
    Export:
      Name: !Sub '${AWS::StackName}-oCloudTrail'