AWSTemplateFormatVersion: 2010-09-09
Description: "Creates eks Cluster Control Plane"

Parameters:
  environment:
    Description: Development Envrionment Name
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stage
      - qa
      - prod

  uniqueIdentifier:
    Description: A unique identifier to associate who this pipeline is for
    Type: String
    Default: uniqueId

  applicationName:
    Description: application name this topic is for
    Type: String

  vpcId:
    Type: AWS::EC2::VPC::Id

  subnetId:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "select two"

  securityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>

  kubernetesVersion:
    Type: String
    Default: 1.17


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Application Information"
        Parameters:
          - environment
          - uniqueIdentifier
          - applicationName
      - Label:
          default: "Control Plane Network Information"
        Parameters:
          - vpcId
          - subnetId
          - securityGroupIds
          - kubernetesVersion
    ParameterLabels:
      environment:
        default: Development environment for this template
      uniqueIdentifier:
        default: A unique Identifier to prefix the topic with
      applicationName:
        default: The name of the application or project that will use this topic
      kubernetesVersion:
        default: The version of kubernetes to install


Resources:
  eksControlPlane:
    DependsOn: eksServiceRole
    Type: AWS::EKS::Cluster
    Properties:
      Name:  !Join [ "-", [ !Ref uniqueIdentifier, !Ref environment, !Ref applicationName, "eks-cluster" ]]
      Version: !Ref kubernetesVersion
      RoleArn: !GetAtt eksServiceRole.Arn
      EncryptionConfig:
        - Provider:
            KeyArn: !GetAtt eksCustomManagedKey.Arn
          Resources:
            - secrets
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref eksControlSecurityGroup
        SubnetIds:
          - !Select [0, !Ref subnetId]
          - !Select [1, !Ref subnetId]



  eksServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${uniqueIdentifier}-${environment}-${applicationName}-eks-service-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  eksCustomManagedKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${uniqueIdentifier}-${environment}-${applicationName}-cmk
      TargetKeyId: !Ref eksCustomManagedKey

  eksCustomManagedKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Key to encrypt EKS secrets
      Enabled: true
      KeyPolicy:
        Version: 2012-10-17
        Id: !Sub ${uniqueIdentifier}-${environment}-${applicationName}-cmk
        Statement:
          - Sid: Allow Administration of Key
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - kms:*
            Resource: "*"
          - Sid: Allow use of Key
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt eksServiceRole.Arn
            Action:
              - kms:Decrypt
            Resource: "*"

  eksControlSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${uniqueIdentifier}-${environment}-${applicationName}-eksControl-sg
      GroupDescription: Security Group for EC2 instance
      VpcId: !Ref vpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 10.0.0.0/0
      Tags:
        - Key: environment
          Value: !Ref environment
        - Key: application
          Value: !Ref applicationName


Outputs:
  EksRoleArn:
    Description: EKS role for creating aws resources
    Value: !GetAtt eksServiceRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-RoleArn"
