AWSTemplateFormatVersion: 2010-09-09
Description: "service role for lambda deployment"

# testing to see if this thing needs to be built first so that you can passrole to it.


Parameters:
  uniqueIdentifier:
    Type: String
    Description: "A unique organization identifier (ie: nelsone). This will be the prefix for created resources."
    Default: nelsone

  applicationName:
    Type: String
    Description: "the name of the application that the pipeline builds. The unique identifier will be added as a prefix."



Resources:
  lambdaDeploymentRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join [ "-", [ !Ref uniqueIdentifier, !Ref applicationName, "lambda-deployment-service-role" ]]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
                - lambda.amazonaws.com
                - codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: !Join [ "-", [ !Ref uniqueIdentifier, !Ref applicationName, "lambda-deployment-service-role-policy" ]]
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudformation:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'logs:*'
                Resource:
                  - 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                Resource:
                  - 'arn:aws:s3:::*'
              - Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:PutRolePolicy
                  - iam:AttachRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:DetachRolePolicy
                  - iam:PassRole
                  - iam:GetRolePolicy
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - lambda:GetFunction
                  - lambda:CreateFunction
                  - lambda:UpdateFunctionCode
                  - lambda:DeleteFunction
                  - lambda:GetFunctionConfiguration
                  - lambda:ListTags
                  - lambda:TagResource
                  - lambda:UntagResource
                  - lambda:AddPermission
                  - lambda:UpdateFunctionConfiguration
                  - lambda:RemovePermission
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - events:DescribeRule
                  - events:PutRule
                  - events:RemoveTargets
                  - events:PutTargets
                  - events:DeleteRule
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                 - apigateway:POST
                 - apigateway:PATCH
                 - apigateway:DELETE
                 - apigateway:GET
                Resource:
                  - '*'